### ISSUE TITLE
Minecraft: Windows 10 Edition Compatibility issue

### ISSUE THREAD

**Issue by JERisBRISK** [mstefarov/fNbt#31]
I just tried using fNbt to load the level.dat file for a Minecraft Windows 10 Edition save and was met with two exceptions.

The first was that it was unable to detect the compression format:

```
System.IO.InvalidDataException: Could not auto-detect compression format.
   at fNbt.NbtFile.DetectCompression(Stream stream)
```

I tried to remedy that by explicitly calling `nbtFile.LoadFromFile(levelDatFile, NbtCompression.None, null)`. This worked, but the next error I encountered was:

```
fNbt.NbtFormatException: Given NBT stream does not start with a TAG_Compound
   at fNbt.NbtFile.LoadFromStreamInternal(Stream stream, TagSelector tagSelector)
```

So, whatever Mojang did for the Windows 10 Edition of Minecraft seems to have introduced some compatibility issues with fNbt.

**Comment by tryashtar** [comment]
Try this:
```cs
 var file = new NbtFile();
 file.BigEndian = false;
 byte[] data = File.ReadAllBytes(levelDatFile);
 file.LoadFromBuffer(data, 8, data.Length - 8, NbtCompression.None);
```

**Comment by brammie15** [comment]
> Try this:
> 
> ```cs
>  var file = new NbtFile();
>  file.BigEndian = false;
>  byte[] data = File.ReadAllBytes(levelDatFile);
>  file.LoadFromBuffer(data, 8, data.Length - 8, NbtCompression.None);
> ```

How do i save the file then?

**Comment by mstefarov** [comment]
Fixed in fNbt 2.0.0, as far as fNbt can fix it. Two things were going on:

1. Bedrock's `level.dat` starts with an 8-byte header (a little-endian storage version and the payload length) that is not NBT at all. That is what tripped auto-detection and the "does not start with a TAG_Compound" check. fNbt still leaves it to the caller, since it is a file-format detail rather than NBT.
2. The payload is little-endian NBT with Bedrock's own rules (no `TAG_Long_Array`, strings up to 32,767 bytes). In fNbt 2.0 that is `NbtFlavor.Bedrock`, and the `BigEndian` setter from the workaround above is gone.

Here is how to load and save, header included:

```cs
var file = new NbtFile(NbtFlavor.Bedrock);
int version;
using (var input = new BinaryReader(File.OpenRead(levelDatFile))) {
    version = input.ReadInt32();     // storage version
    input.ReadInt32();               // payload length. fNbt doesn't need it to read
    file.LoadFromStream(input.BaseStream, NbtCompression.None);
}

// ... edit file.RootTag ...

byte[] payload = file.SaveToBuffer(NbtCompression.None);
using (var output = new BinaryWriter(File.Create(levelDatFile))) {
    output.Write(version);
    output.Write(payload.Length); // recomputed on save
    output.Write(payload);
}
```

`BinaryReader` and `BinaryWriter` are always little-endian, which is what the header needs. If everything in your app is Bedrock, `NbtOptions.DefaultFlavor = NbtFlavor.Bedrock;` at startup makes a plain `new NbtFile()` do the right thing.

Release notes: https://github.com/mstefarov/fNbt/releases/tag/v2.0.0
API reference: https://fcraft.net/fnbt/v2.0.0/
